apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-secret
  namespace: graph
spec:
  encryptedData:
    access-key : AgDiKSzJw0oJVDvDhjGIhCR7H7OeVex9xASiwmkAlvQKprhEKgi8Cq+L3BbL7TLUsgPH0cZkhkRfSLmgcanCTwt5aIWd/Tsdbu+GkfZwfgKh1N8e1GjyCi80dYuR7yQ9VPOW6iNdKAbm7UYF2brOmYf9QAnYbp5yeznkopKlw9ZgRlAThTDHsTcJwCeAPWAQupWxsS2AVjkX2ybIQq8imYb3p/bT91iOx6nbbDxAyUp9Dp6LWht3y2k5MOgCEXDqCZlWjSTQddJQokfke5Y1E28Lfo27p7BWJ1sq3Dp+ytacWGPU8LPXpr8DapHgwLZQQekleLvOQx6o/s+euyhzGIL7OfELD4l5VZSfG+eR9pxu/sOI0asrMYJrswfLvPrxvWoBBiLqohtuoUt5Nyq8BIzPfOwwpqr/30NjDWByXzcFOd8WbBwpADUzEVWRjTnNt9D0q/LSTwejg7Y+0t8pAIBlO8gDyTb1JLZTouDeb0vKBrpj7S6GQUoQzVAv1ADPeEfXmlnVOaZjcXub6O5VQYsFGHD0pu0gSjsqZrbafFO/eweQlaXtET5T33GRTWbhC6rtxDnD7fVbm60vxrRYuOJQs8AkmERLkRA8NA3IjslvJyEpO4YPStK+rmS2mPatk0IBnMTZNjiNiAWhQCbQL8CG7dVwCkcFX7IsmSlhHuyXUXjQKTB4IY17THAK6UGUi3JsyQHJXunI18yZioyf1U9TR+iv2PxeS9S8GO1iM594tVjIAonU0v5icCa6iIdOVTGqS8BEmEe8HQ==
  template:
    metadata:
      creationTimestamp: null
      name: s3-secret
      namespace: graph

