[workspace]
default-members = ["processed_data"]
members = ["models", "processed_data"]
resolver = "2"

[workspace.dependencies]
sea-orm = { version = "0.12.14", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
] }
