version: "3.8"

services:
  graph-data-processing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached,z
    command: sleep infinity
    environment:
      DATABASE_URL: mysql://root:rootpassword@ispyb/ispyb_build
      LOG_LEVEL: DEBUG
